# Generated by Django 6.0.4 on 2026-04-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Sin previo', 'Sin previo'), ('Grabando', 'Para Grabar'), ('Entregar', 'Para Entregar')], default='Sin_previo', max_length=20)),
            ],
        ),
    ]
