# Generated by Django 6.0.4 on 2026-04-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_fecha_task_hora_task_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='anticipo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='task',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
