# Generated by Django 6.0.4 on 2026-04-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_task_anticipo_task_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
