# Generated by Django 6.0.4 on 2026-04-29 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_task_product_alter_task_anticipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
