# Generated by Django 6.0.4 on 2026-04-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fecha',
            field=models.DateField(default='2026-01-01'),
        ),
        migrations.AddField(
            model_name='task',
            name='hora',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='task',
            name='nombre',
            field=models.CharField(default='Cliente', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='numero_telefono',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='tipografia',
            field=models.CharField(default='Arial', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='Product',
            field=models.CharField(default='Sin producto', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estado',
            field=models.CharField(choices=[('Sin previo', 'Sin previo'), ('Grabando', 'Para Grabar'), ('Entregar', 'Para Entregar')], default='Sin previo', max_length=20),
        ),
    ]
