# Generated by Django 6.0.4 on 2026-04-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_task_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Product',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='anticipo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='numero_telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='tipografia',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
